version: 2
updates:
  - package-ecosystem: "npm"
    directories:
      - "/"
      - "/client"
      - "/server"
      - "/shared"
    schedule:
      interval: "weekly"
    groups:
      npm-workspaces:
        patterns:
          - "*"
        group-by: "dependency-name"
    open-pull-requests-limit: 0

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 0
